{% set name = "geoglows" %}
{% set version = "0.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0921c2e275093f2a2e18ffbaf12d53a6bc5c2c0bd83d9c13fc795173d2c45b4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - requests
    - plotly
    - jinja2
    - pandas
    - shapely
    - scipy

test:
  imports:
    - geoglows

about:
  home: https://github.com/rileyhales/geoglows
  summary: A tool for retrieving Streamflow from the GEOGloWS ECMWF Streamflow service developed by Riley Hales as part of a Master's Thesis in Civil and Environmental Engineering at Brigham Young University
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://geoglows.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales
