{% set name = "geoglows" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95fe28ebc1a61553ac781a83a3ce03331bf6824ff341142c5cf3d6227b99785e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - pandas
    - plotly >=4.6
    - jinja2
    - shapely
    - scipy
    - numpy
    - hydrostats
    - HydroErr

test:
  imports:
    - geoglows

about:
  home: https://github.com/BYU-Hydroinformatics/geoglows
  summary: A tool for retrieving Streamflow from the GEOGloWS ECMWF Streamflow Service
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://geoglows.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales
    - rfun
