{% set name = "geoglows" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c1a4168f79a0b17d9b8e711df1f443dce29c91c58c4d4a639a47f25cc03389d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - requests
    - plotly
    - jinja2
    - pandas
    - shapely
    - scipy

test:
  imports:
    - geoglows

about:
  home: https://github.com/rileyhales/geoglows
  summary: A tool for retrieving Streamflow from the GEOGloWS ECMWF Streamflow service developed by Riley Hales as part of a Master's Thesis in Civil and Environmental Engineering at Brigham Young University
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://geoglows.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales
