{% set name = "geoglows" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdf32e42a76fc3e7602dca83818e1b0ef726b51fcc7a0f00c390e219b38b0a49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - pandas
    - plotly >=5
    - scipy
    - numpy
    - hydrostats
    - HydroErr
    - s3fs
    - xarray
    - zarr
    - fastparquet
    - dask

test:
  imports:
    - geoglows

about:
  home: https://github.com/BYU-Hydroinformatics/geoglows
  summary: A tool for retrieving modeled river discharge from the GEOGLOWS data service
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://geoglows.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales
    - msouff
