{% set name = "geoglows" %}
{% set version = "1.8.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a6f1a0deefd770b7b2a4602a300e2cedc267ba0d57b876e147699ed02e9d8aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dask >=2024
    - fastparquet
    - HydroErr
    - hydrostats
    - numpy >=1
    - pandas >=1
    - plotly >=5
    - requests
    - scipy
    - s3fs >=2024
    - xarray >=2024
    - zarr ==2.18.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - geoglows

about:
  home: https://github.com/geoglows/pygeoglows
  summary: A tool for retrieving modeled river discharge from the GEOGLOWS data service
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://geoglows.readthedocs.io

extra:
  recipe-maintainers:
    - rileyhales
    - msouff
